os: osx
osx_image: xcode8
sudo: false
language: objective-c

env:
  - NODE_VERSION="4"
  - NODE_VERSION="5"
  - NODE_VERSION="6"

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'

script:
  - npm run clean
  - npm run test
before_install:
  - export ANDROID_HOME=/usr/local/opt/android-sdk
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm use $NODE_VERSION
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - brew update > /dev/null;
  - brew install android-sdk dash gnu-sed jpeg python3;
  - echo y | android --verbose update sdk --no-ui --all --filter platform-tools,build-tools-24.0.2;
  - npm install -g npm
  - npm install -g nativescript
  - npm install
  # Output useful info for debugging
  - node --version
  - npm --version
  - pod repo update
